export const UPDATE_CURRENT_LEVEL = 'UPDATE_CURRENT_LEVEL';
export const SET_SOUND_FX = 'SET_SOUND_FX';
export const TOGGLE_VOLUME = 'TOGGLE_VOLUME';
export const SET_CURRENT_SUM = 'SET_CURRENT_SUM';
export const EVALUATE_RESULT = 'EVALUATE_RESULT'